### ISSUE TITLE
SqlQuery type instead of string type 

### ISSUE THREAD

**Issue by Clonkk** [GULPF/tiny_sqlite#11]
Right now query proc use string type. I think it would be better (arguable, safer) to use the type SqlQuery from https://nim-lang.org/docs/db_common.html.

**Comment by GULPF** [comment]
I'd be happy to hear a some arguments for it, but I've never liked the `SqlQuery` type much. Although it prevents things like `sql"SELECT * From Foo WHERE Name = $1" % [someVariable]` I suspect a user that is not aware of the danger will simply try `("SELECT * From Foo WHERE Name = $1" % [someVariable]).sql` instead.

**Comment by Clonkk** [comment]
Sql injection is the main argument I had in mind. 
It also helps sanitize API a bit by not treating sql statement as native string (also that is a minor point).

Out of curiosity, what do you dislike in SqlQuery type ?

**Comment by GULPF** [comment]
> Out of curiosity, what do you dislike in SqlQuery type ?

Because I don't see how it prevents SQL injections in practice. Nothing prevents the API user from constructing an SQL query string in dangerous ways and then converting the string to the distinct string type.
