### ISSUE TITLE
Error: attempting to call undeclared routine: 'iterate'

### ISSUE THREAD

**Issue by waspoza** [GULPF/tiny_sqlite#12]
Hi, i'm trying to compile the test program:

```
import tiny_sqlite, std / options

let db = openDatabase("aaaa.db")
db.execScript("""
CREATE TABLE Person(
    name TEXT,
    age INTEGER
);

INSERT INTO
    Person(name, age)
VALUES
    ("John Doe", 47);
""")

db.exec("INSERT INTO Person VALUES(?, ?)", "Jane Doe", nil)

for row in db.iterate("SELECT name, age FROM Person"):
    let (name, age) = row.unpack((string, Option[int]))
    echo name, " ", age
```

And im getting this error:
```
piotr@Intel-NUC:~/nim$ nim c tsqlite.nim
Hint: used config file '/snap/nim-lang/1111/config/nim.cfg' [Conf]
Hint: used config file '/snap/nim-lang/1111/config/config.nims' [Conf]
...............
/home/piotr/nim/tsqlite.nim(18, 14) Error: attempting to call undeclared routine: 'iterate'
```

With last loop commented out it compiles and runs.

Nim version 1.4.2 from snap on Ubuntu.

**Comment by SolitudeSF** [comment]
documentation is ahead of release version. it should be `rows`. or install HEAD.

**Comment by waspoza** [comment]
I see. Thank you for clarification, it works now.

**Comment by telatin** [comment]
Probably related to this, but I'm not getting how to freeze the commit to be used

Code
```python
let db = openDatabase("test.db")
let value = db.one("SELECT name FROM sqlite_master WHERE type='table' AND name='?';", "slurmjobs")
```

Error
```
Error: attempting to call undeclared routine: 'one'
```

I tried with `nimble install tiny_sqlite@#8fe760d91da18faecdbe32a7038bfd4661bcf1b6` but didn't work, while `HEAD` did: to make the process reproducible, what hash should I use?

**Comment by SolitudeSF** [comment]
add `requires "tiny_sqlite#8fe760d91da18faecdbe32a7038bfd4661bcf1b6"` to $your_project.nimble file and build with nimble

**Comment by telatin** [comment]
Thanks!

**Comment by joenano** [comment]
Someone responded with wide eyes emoji but people searching for a nim sqlite library are going to arrive here, the example doesnt run and it has just been left as an open issue for over a year. Not great for nim. Readme should at least be updated to a working example if the issue isnt being fixed.

**Comment by GULPF** [comment]
New tag pushed, better late then never...
