### ISSUE TITLE
Looks really compatible with Python sqlite3

### ISSUE THREAD

**Issue by hashbackup** [GULPF/tiny_sqlite#3]
I haven't tried it yet, but this looks pretty awesome as a substitute for Python's sqlite3 module.  I posted some comments about the db_sqlite module here: https://github.com/nim-lang/Nim/issues/13559

A great addition to this would be a prepared stmt cache like Python's sqlite3 has.  I think it caches something like the last 50 prepared statements, though you can change that size (I think - never messed with it).  A simple way is to hash the string, check a Nim table to see if it's already been prepared, and if so, use the bind calls to associate new parameters with the already-prepared statement.

In my tests (on that Nim GH issue), Python was about 30% faster than Nim, I'm guessing because it avoided recompiling statements on every exec.

**Comment by GULPF** [comment]
Thanks for the suggestion, it sounds like a good idea for this library. I made some tests with a simple statement cache and it seems promising, I'll finish it up in the next few days if I have the time :)

**Comment by GULPF** [comment]
Implemented in https://github.com/GULPF/tiny_sqlite/commit/ecab3626afa599e0078883d43d4127e78698e953

**Comment by hashbackup** [comment]
This looks great!  I'm not so sure about Nim anymore - it seems a little flaky based on the couple of weeks I've messed with it.  But since you took time to implement the stmt cache, I'll at least try out my Nim/Python SQLite benchmark with tiny-sqlite to see what kind of improvement the cache makes.  Maybe it'll motivate me to give Nim another chance.  Thanks again!

**Comment by hashbackup** [comment]
Wow, you hit a homerun on this!  I updated that Nim issue with benchmark results for your library: it's 3x faster than Python, and 4x faster than Nim's db_sqlite library.  Nice job!
