### ISSUE TITLE
Suggestion: db.row for selecting single row

### ISSUE THREAD

**Issue by hashbackup** [GULPF/tiny_sqlite#4]
To read a single row with tiny_sqlite, I used:
```
for row in db.rows("select v from t where k = 13"):
  let (v,) = row.unpack((int,))
  echo v
```
It seems a little odd to me because the for + db.rows implies processing multiple rows.  Maybe it could be made clearer by adding a break to the end.

A simpler, and I think clearer alternative would be something like:
```
  let (v,) = db.row("select v from t where k = 13").unpack((int,))
```
I added this to my copy of tiny_sqlite and it works fine:
```
proc row*(db: DbConn, sql: string,
          params: varargs[DbValue, toDbValue]): seq[DbValue] =
    ## Executes ``sql`` and returns 1 row.
    for row in db.rows(sql, params):
        return row
```
Here's the original test program using db.rows:
```
import os
import tiny_sqlite

const
  dbname = "bttest4.nim.db"

let nrows = 1_000_000
#let nrows = 100
os.removeFile(dbname)

let db = openDatabase(dbname)

db.exec("""create table t (
  k    integer primary key,
  v    integer)""")

db.transaction:
  for i in 0..<nrows:
    db.exec("insert into t values (?,?)", i, i)

db.transaction:
  for i in 0..<3:
    for j in 0..<nrows:
      for row in db.rows("select v from t where k = ?", j):
        let (v,) = row.unpack((int,))
        db.exec("update t set v = ? where k = ?", v+1, j)

for row in db.rows("select v from t where k = 13"):
  let (v,) = row.unpack((int,))
  echo v

db.close()
```
Here's a snippet from the new version, to get a visual of the difference.  It's only 2 lines shorter but looks clearer to me:
```
db.transaction:
  for i in 0..<3:
    for j in 0..<nrows:
      let (v,) = db.row("select v from t where k = ?", j).unpack((int,))
      db.exec("update t set v = ? where k = ?", v+1, j)

let (v,) = db.row("select v from t where k = 13").unpack((int,))
echo v
```
Mistakenly switching db.row and db.rows could be a source of bugs, but db.1row isn't legal, and db.aRow, db.oneRow, and db.singleRow seem a little much.

Another option could be something like db.unpackRow that accepts a query string:
```
let (v,) = db.unpackRow("select v from t where k = 13", (int,))
echo v
```
That's not as flexible because you can't get the row itself.  Nim's db_sqlite has GetValue to read the first value from a row, but that won't work for a multi-value row, like selecting count(*), avg(size).

**Comment by GULPF** [comment]
I agree that something like `row` should exist, but I'm not sure about the naming. `row`/`rows` is to similar imo. The `rows` name is taken from db_sqlite and I wouldn't mind changing it. How about `value`/`one`/`all` as the equivalents of db_sqlite's `getValue`/`getRow`/`getAllRows`? Short but still understandable I think

**Comment by hashbackup** [comment]
Sounds good.  If you want to change <rows>, you could call it <many>.
