### ISSUE TITLE
FYI: SQLite supports nested transactions via savepoints

### ISSUE THREAD

**Issue by hashbackup** [GULPF/tiny_sqlite#5]
I noticed in the tiny_sqlite.nim source there is a comment that SQLite doesn't support nested transactions.  Sort of true, but it does support them with nested savepoints.  I have not personally used savepoints, though they would come in handy for HashBackup (I'm the author) to start a savepoint at the beginning of a new file and either commit the savepoint or roll it back depending on whether the file actually was saved.  Right now is kind of messy with a lot of try/except/finally code that has to make sure the db state is correct.  With savepoints, I could let an exception bubble up further and rollback that one file's savepoint.

Feel free to close this - just letting you know about savepoints.

**Comment by GULPF** [comment]
I'm aware of save points, but don't think the transaction template should deal with them. It could be implemented as a separate template however
